<a href="https://colab.research.google.com/github/vasukondreddy/PyTorch/blob/main/1_Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
a=torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.2820, 0.4937, 0.1836],
        [0.2195, 0.9580, 0.9980]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# arange
print("Using arange ->",torch.arange(0,10,2))

# using linspace
print("using linspace ->",torch.linspace(0,10,10)) # it rwturn 10 number b/w 0-10

#using eye - a square matrix with 1s on the diagonal and 0s elsewhere.
print("using eye ->", torch.eye(5))

# using full - (2,3) are size and 5 is printable num
print("using full ->",torch.full((3,3),5))

Using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) #with same x size creating new tensor

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067247193233829173, 4121702084124488497, 6498752773544555822]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
#while crating tensor how to define data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# how to change execting tensor datatype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

### 1. Scalar operation

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition

x+2
#substraction
x-2

#maltiplication
x*3

# division
x/3

# int division
(x*100)//3

# mod
((x%100)//3)%2

# power
x**2

tensor([[0., 0.],
        [0., 0.]])

### 2. Element wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)


tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
# add
a+b
#substraction
a-b

#maltiplication
a*b

# division
a/b

# mod
a%b

#power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d= torch.tensor([1.9,2.3,3.7,4.4])


In [ ]:
# round
torch.round(d)

# cell
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [ ]:
# sum
torch.sum(e)

tensor(42.)

In [ ]:
# sum along columns
torch.sum(e,dim=0)

tensor([14., 16., 12.])

In [ ]:
# sum along rows
torch.sum(e,dim=1)

tensor([17., 25.])

In [ ]:
# mean
torch.mean(e)

tensor(7.)

In [ ]:
# mean along col
torch.mean(e,dim=0)

tensor([7., 8., 6.])

In [ ]:
# median
torch.median(e)

tensor(7.)

In [ ]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(5.)


In [ ]:
# standard deviation
torch.std(e)

tensor(1.7889)

In [ ]:
# variance
torch.var(e)

tensor(3.2000)

In [ ]:
# argmax
torch.argmax(e) # it gives position of big value

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1],
        [5, 5],
        [0, 4]])


In [ ]:
# matrix multiplaction
torch.matmul(f,g)

tensor([[42, 60],
        [82, 59]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
# dot product
torch.dot(vector1,vector2)


tensor(11)

In [ ]:
# transpose
f

tensor([[2, 6, 7],
        [7, 8, 3]])

In [ ]:
torch.transpose(f,0,1)

tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [ ]:
# determinant
torch.det(h)

tensor(-6.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

### 5.Comparison opearation

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[0, 4, 2],
        [7, 1, 1]])
tensor([[5, 4, 4],
        [1, 1, 2]])


In [ ]:
#grater than
i>j

tensor([[False, False, False],
        [ True, False, False]])

In [ ]:
# less than
i<j

tensor([[ True, False,  True],
        [False, False,  True]])

In [ ]:
# equal to
i==j

tensor([[False,  True, False],
        [False,  True, False]])

In [ ]:
# not equal to
i!=j

tensor([[ True, False,  True],
        [ True, False,  True]])

In [ ]:
# greater than equal to
i>=j

tensor([[False,  True, False],
        [ True,  True, False]])

In [ ]:
# less than equal to
i<=j

tensor([[ True,  True,  True],
        [False,  True,  True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0,high=10,dtype=torch.float32)
k

tensor([[1., 0., 2.],
        [1., 2., 7.]])

In [ ]:
# log
torch.log(k)

tensor([[0.0000,   -inf, 0.6931],
        [0.0000, 0.6931, 1.9459]])

In [ ]:
# exp
torch.exp(k)

tensor([[2.7183e+00, 1.0000e+00, 7.3891e+00],
        [2.7183e+00, 7.3891e+00, 1.0966e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 0.0000, 1.4142],
        [1.0000, 1.4142, 2.6458]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.5000, 0.8808],
        [0.7311, 0.8808, 0.9991]])

In [ ]:
# soft max - to find this input should in folat dtype
torch.softmax(k,dim=0)

tensor([[0.5000, 0.1192, 0.0067],
        [0.5000, 0.8808, 0.9933]])

In [ ]:
# relu
torch.relu(k)

tensor([[1., 0., 2.],
        [1., 2., 7.]])

## Inplace Operator

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])
tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])


In [ ]:
# when we do m+n the result stored in new memory and the m is not updating
# so for that
m.add_(n)

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [ ]:
m

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [ ]:
n

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
torch.relu(m)

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [ ]:
m.relu_()
# to make permenenet updates use underscore(_) after function like "relu_"

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [ ]:
m

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

## Coping a Tensor

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.5688, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
b=a # with this if we make updates in a it reflect to b as well

In [ ]:
b

tensor([[0.5688, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
a[0][0]=0
a

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
b

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
id(a)

137705566329200

In [ ]:
id(b) # means data is stord in same memory that why if we update one another also update

137705566329200

In [ ]:
b=a.clone() # to overcome from the above problem we use this
a

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
b

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
a[0][0]=10
a

tensor([[10.0000,  0.0634,  0.8993],
        [ 0.2732,  0.3397,  0.1879]])

In [ ]:
b

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
id(a)

137705566329200

In [ ]:
id(b)

137704838353872

## Tensor Operations on GPU

In [ ]:
torch.cuda.is_available() # to check gpu is available or not

True

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating new tensor on GPU
torch.rand((2,3),device=device) # it is created insise gpu

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
a # it is created in CPU

tensor([[0.5534, 0.2682, 0.9556],
        [0.9761, 0.5934, 0.3124]])

In [ ]:
b=a.to(device)
b+5

tensor([[5.5534, 5.2682, 5.9556],
        [5.9761, 5.5934, 5.3124]], device='cuda:0')

## Reshaping Tensors

In [ ]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

# Explanation of (2, 2, 2, 2)
# This is a 4-dimensional tensor with:

# 2 blocks

# each block has 2 matrices

# each matrix has 2 rows

# each row has 2 elements


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten - is used to flatten a tensor a into a 1D (one-dimensional) tensor in PyTorch
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.9431, 0.8519, 0.9815, 0.1132],
         [0.4783, 0.4436, 0.3847, 0.4521],
         [0.5569, 0.9952, 0.0015, 0.0813]],

        [[0.4907, 0.2130, 0.4603, 0.1386],
         [0.0277, 0.5662, 0.3503, 0.6555],
         [0.7667, 0.2269, 0.7555, 0.6458]]])

In [ ]:
# permute -  permute() function is used to reorder the dimensions of a tensor
b.permute(2,0,1).shape # it change the shape()

torch.Size([4, 2, 3])

In [ ]:
# unsequeze - unsqueeze() is used to add a new dimension (axis) of size 1 at the specified position (dim) in a tensor.
# image size
c= torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
# squeeze - squeeze() is used to remove all dimensions of size 1 from a tensor — it squeezes out unnecessary axes.
d= torch.rand(1,20)
d.squeeze(0).shape # it remove 1 of index 0

torch.Size([20])

## NumPY and PyTorch

In [ ]:
import numpy as np

In [ ]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c) # converting numpy to tensor


tensor([1, 2, 3])