<a href="https://colab.research.google.com/github/vasukondreddy/PyTorch/blob/main/2_1_pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## train test split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [ ]:
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_trst=scaler.transform(X_test)

In [ ]:
X_train

array([[-0.37068466, -0.64352134, -0.42711022, ..., -0.86280257,
        -0.85301937, -1.09547054],
       [ 0.35060028,  0.70477953,  0.30936701, ...,  0.11272905,
         0.42983108,  0.70912825],
       [-0.49186053, -0.17662661, -0.52614648, ..., -0.47124394,
         0.11883703, -0.67947885],
       ...,
       [ 1.15843941,  0.57496002,  1.08487125, ..., -0.35821197,
        -0.87569602, -1.01602955],
       [-0.5986107 ,  1.26960828, -0.5848968 , ...,  0.07602043,
        -0.50315106, -0.10728899],
       [-0.30721158,  0.33354128, -0.33730616, ..., -0.7994802 ,
         0.46384606, -1.08205145]])

In [ ]:
y_train

69     B
184    M
107    B
6      M
176    B
      ..
306    B
144    B
197    M
445    B
150    B
Name: diagnosis, Length: 455, dtype: object

## Label Enoding

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,

## Numpy arrays to PyTorch tensor

In [ ]:
# X_train_tensor=torch.from_numpy(X_train).float()
# X_test_tensor=torch.from_numpy(X_test).float()
# y_train_tensor=torch.from_numpy(y_train).long()
# ytest_tensor=torch.form_numpy(y_test).long()

import torch

# Ensure conversion works whether it's a DataFrame or NumPy array
import numpy as np

# If already NumPy, this does nothing
X_train_np = X_train if isinstance(X_train, np.ndarray) else X_train.to_numpy()
X_test_np = X_test if isinstance(X_test, np.ndarray) else X_test.to_numpy()
y_train_np = y_train if isinstance(y_train, np.ndarray) else y_train.to_numpy()
y_test_np = y_test if isinstance(y_test, np.ndarray) else y_test.to_numpy()

# Now convert to tensors
X_train_tensor = torch.from_numpy(X_train_np).float()
X_test_tensor = torch.from_numpy(X_test_np).float()
y_train_tensor = torch.from_numpy(y_train_np).long()
y_test_tensor = torch.from_numpy(y_test_np).long()


In [ ]:
X_test_tensor

tensor([[9.5040e+00, 1.2440e+01, 6.0340e+01,  ..., 6.2270e-02, 2.4500e-01,
         7.7730e-02],
        [1.2870e+01, 1.9540e+01, 8.2670e+01,  ..., 6.3840e-02, 3.3130e-01,
         7.7350e-02],
        [1.4040e+01, 1.5980e+01, 8.9780e+01,  ..., 7.4530e-02, 2.7250e-01,
         7.2340e-02],
        ...,
        [1.1840e+01, 1.8940e+01, 7.5510e+01,  ..., 6.9130e-02, 2.5350e-01,
         7.9930e-02],
        [1.1900e+01, 1.4650e+01, 7.8110e+01,  ..., 6.0420e-02, 2.7270e-01,
         1.0360e-01],
        [1.1870e+01, 2.1540e+01, 7.6830e+01,  ..., 8.7500e-02, 2.3050e-01,
         9.9520e-02]])

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [ ]:
# class MySimpleNN():
#   def __init__(self,X):

#     self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
#     self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

#   def forward(self,X):
#     X = X.to(torch.float64)
#     z=torch.matmul(X,self.weights) + self.bias
#     y_pred=torch.sigmoid(z)
#     return y_pred

#   def loss_function(self,y_pred,y):
#     # clamp predictions to avoid log(0)
#     epsilon = 1e-7
#     y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

#     # loss calculation
#     loss =-(y * torch.log(y_pred) + (1- y) * torch.log(1-y_pred)).mean()
#     return loss

import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):

    out=self.linear(features)
    out=self.sigmoid(out)

    return out

  # def loss_function(self,y_pred,y):
  # # clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

  #   # loss calculation
  #   loss =-(y * torch.log(y_pred) + (1- y) * torch.log(1-y_pred)).mean()
  #   return loss



## Importing Parameters

In [ ]:
learning_rate=0.1
epochs=25


In [ ]:
# define loss function
loss_function=nn.BCELoss()

In [ ]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training Pipeline

In [ ]:
# create model
model=MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
# model.parameters() is an iterator over all the trainable parameters(weights and biases)

# define loop
for epoch in range(epochs):

# forward pass
  y_pred = model(X_train_tensor)
  print(y_pred)
# loss calclution
  loss = loss_function(y_pred,y_train_tensor.view(-1,1).float())

# clear gradients
  optimizer.zero_grad()
# back propogation
  loss.backward()

# parameter update
  optimizer.step()

  # # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  # print loss in each  epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Streaming output truncated to the last 5000 lines.
        [0.1839],
        [0.1839],
        [0.1028],
        [0.0236],
        [0.9775],
        [0.9969],
        [0.0980],
        [0.1260],
        [0.1353],
        [0.2380],
        [0.0030],
        [0.6041],
        [0.1737],
        [0.0351],
        [0.9914],
        [0.0619],
        [0.9746],
        [0.9274],
        [0.2325],
        [0.9871],
        [0.0798],
        [0.1081],
        [0.0903],
        [0.1543],
        [0.1380],
        [0.4754],
        [0.7240],
        [0.0128],
        [0.2046],
        [0.1592],
        [0.9383],
        [0.6245],
        [0.5560],
        [0.6404],
        [0.9113],
        [0.9622],
        [0.2928],
        [0.1092],
        [0.2352],
        [0.1420],
        [0.3440],
        [0.9663],
        [0.8036],
        [0.0682],
        [0.0827],
        [0.8476],
        [0.9528],
        [0.1421],
        [0.5820],
        [0.9650],
        [0.1863],
        [0.2499],
        [0.19

In [ ]:
# class MySimpleNN:
#     def __init__(self, X):
#         self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
#         self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

#     def forward(self, X):
#         X = X.to(torch.float64)
#         z = torch.matmul(X, self.weights) + self.bias
#         y_pred = torch.sigmoid(z)
#         return y_pred

#     def loss_function(self, y_pred, y):
#         epsilon = 1e-7
#         y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
#         loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
#         return loss


# # --- Training Loop ---

# learning_rate = 0.1
# epochs = 25

# # Create model
# model = MySimpleNN(X_train_tensor)

# for epoch in range(epochs):
#     # Forward pass
#     y_pred = model.forward(X_train_tensor)

#     # Loss calculation
#     loss = model.loss_function(y_pred, y_train_tensor)

#     # Backpropagation
#     loss.backward()

#     # Parameter update
#     with torch.no_grad():
#         model.weights -= learning_rate * model.weights.grad
#         model.bias -= learning_rate * model.bias.grad

#     # Zero gradients
#     model.weights.grad.zero_()
#     model.bias.grad.zero_()

#     # Accuracy (optional but useful)
#     with torch.no_grad():
#         predictions = (y_pred > 0.5).double()
#         accuracy = (predictions == y_train_tensor).sum().item() / len(y_train_tensor)

#     # Print loss and accuracy
#     print(f'Epoch: {epoch + 1}, Loss: {loss.item():.4f}, Accuracy: {accuracy:.4f}')


In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.2140,  0.1307,  0.2666,  0.1016,  0.1537,  0.1636,  0.1718,  0.2522,
          0.1734, -0.1997,  0.1357, -0.1097,  0.2704,  0.0151,  0.1165,  0.1846,
          0.1061,  0.0282, -0.1076, -0.2273,  0.3406,  0.1569,  0.3191,  0.3511,
          0.1846, -0.0214,  0.1874,  0.3577,  0.2730, -0.0060]],
       requires_grad=True)

In [ ]:
# mdoel evaluation

with torch.no_grad():
  y_pred = model.forward(X_train_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy =(y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5354732871055603
