<a href="https://colab.research.google.com/github/vasukondreddy/PyTorch/blob/main/3_PyTorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features): # constructor

    super().__init__() # parent class constructor
    self.linear = nn.Linear(num_features,1) # here 1 indicateds ou[ut features
    self.sigmoid = nn.Sigmoid() # which squashes output values into a range between 0 and 1.
    # sigmoid() Commonly used in binary classification to convert raw outputs to probabilities.

  def forward(self,features): # This is the forward pass of the model, where input data goes through the layers.

    out=self.linear(features)
    out=self.sigmoid(out)

    return out



In [ ]:
# create dataset

features= torch.rand(10,5)

# create model
model=Model(features.shape[1]) # objct created

# call model for forward pass
#model.forward(features)
model(features) # standard way to call model

tensor([[0.6426],
        [0.6598],
        [0.6147],
        [0.6478],
        [0.6427],
        [0.7027],
        [0.6844],
        [0.7013],
        [0.6382],
        [0.6414]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0517, -0.2557,  0.4084,  0.1636,  0.3288]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.2971], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
# visulaize the network
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU() # activation for hidden layer
# in this model we are taking 5inpus 3 hiden layers(use ReLU) hasa 3bias and output as 1
    self.linear2 = nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out

In [ ]:
# create dataset

features= torch.rand(10,5)

# create model
model=Model(features.shape[1]) # objct created

# call model for forward pass
#model.forward(features)
model(features) # standard way to call model

tensor([[0.6367],
        [0.6259],
        [0.6343],
        [0.6307],
        [0.6174],
        [0.6272],
        [0.6305],
        [0.6270],
        [0.6362],
        [0.6204]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.0293,  0.2966, -0.0476, -0.3980,  0.0162],
        [ 0.3787,  0.0300,  0.2446, -0.4438,  0.0337],
        [ 0.2175, -0.2005, -0.3490,  0.2617, -0.1256]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.2601,  0.4071, -0.3805], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.2370,  0.2093,  0.3729]], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([0.4320], requires_grad=True)

In [ ]:
from torchinfo import summary
summary (model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    ## Using Sequential Container to create model easily
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)

    return out

In [ ]:
# create dataset

features= torch.rand(10,5)

# create model
model=Model(features.shape[1]) # objct created

# call model for forward pass
#model.forward(features)
model(features) # standard way to call model

tensor([[0.6285],
        [0.6067],
        [0.6705],
        [0.6126],
        [0.5795],
        [0.6108],
        [0.5864],
        [0.6001],
        [0.5967],
        [0.6291]], grad_fn=<SigmoidBackward0>)